apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: v863abf8q-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:f5ffe13b957c2561d55e87a162fc5e3768f1d28e@sha256:3ff9526b6fd407621c40c1cdecdc927a79bf5d6df752b502c5f9acc9a229c9a9
          name: container-image
